services:

  casdoor:
    container_name: casdoor
    image: casbin/casdoor:latest
    ports:
      - 8000:8000
    volumes:
      - ./conf:/conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
